version: '3.8'

services:
  go_refine_dashboard_be:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile.dev
    container_name: go_refine_dashboard_be
    ports:
      - "2880:8080"
    stdin_open: true
    tty: true
    volumes:
      - ./apps/backend:/app
      - /app/tmp # Giữ lại folder tmp không bị ghi đè ngược ra máy thật
    environment:
      - ENV=development
    networks:
      - app-network

  go_refine_dashboard_fe:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile.dev
    container_name: go_refine_dashboard_fe
    ports:
      - "2881:5173"
    restart: always
    tty: true
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules # Tránh ghi đè/xóa node_modules của container bằng node_modules máy thật
    environment:
      - NODE_ENV=development
    networks:
      - app-network
    depends_on:
      - go_refine_dashboard_be

networks:
  app-network:
    driver: bridge