FROM node:20-alpine

WORKDIR /app

# Copy package.json và lockfile để install dependencies trước
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
RUN npm install

# Copy source code còn lại
COPY . .