FROM golang:1.26-alpine

WORKDIR /app

# Cài đặt git và air để live reload
RUN apk add --no-cache git gcc musl-dev && \
    go install github.com/air-verse/air@latest

# Copy go.mod và go.sum trước để tận dụng cache của Docker
COPY go.mod go.sum ./
RUN go mod download

# Copy toàn bộ source code
COPY . .