FROM golang:1.25-alpine

WORKDIR /app

# Cài đặt git, air để live reload và các công cụ cần thiết cho cgo
RUN apk add --no-cache git gcc musl-dev tzdata && \
    go install github.com/air-verse/air@latest && \
    go install -tags 'mysql' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

# Copy go.mod và go.sum để tận dụng Docker cache layer
COPY go.mod go.sum ./
RUN go mod download

# Copy toàn bộ mã nguồn
COPY . .

# Chạy bằng air với file cấu hình
# CMD ["air", "-c", ".air.toml"]