import React from "react";
import { Accordion, AccordionDetails, AccordionSummary, Avatar, Box, Button, Chip, IconButton, Stack, Switch, Tooltip, Typography } from "@mui/material";
import ExpandMoreIcon from "@mui/icons-material/ExpandMore";
import DragIndicatorIcon from "@mui/icons-material/DragIndicator";
import EditOutlinedIcon from "@mui/icons-material/EditOutlined";
import DeleteOutlineIcon from "@mui/icons-material/DeleteOutline";
import KeyboardArrowUpIcon from "@mui/icons-material/KeyboardArrowUp";
import KeyboardArrowDownIcon from "@mui/icons-material/KeyboardArrowDown";
import ImageOutlinedIcon from "@mui/icons-material/ImageOutlined";
import { IPageSection } from "./page-section-types";
import { SectionCollections } from "./section-collections";

interface Props { section: IPageSection; index: number; total: number; disabled: boolean; onEdit: () => void; onDelete: () => void; onToggle: () => void; onMove: (to: number) => void; onDropAt: (from: number, to: number) => void; onMutatingChange: (active: boolean) => void; }
export const PageSectionCard: React.FC<Props> = ({ section, index, total, disabled, onEdit, onDelete, onToggle, onMove, onDropAt, onMutatingChange }) => <Accordion disableGutters sx={{ border: 1, borderColor: "divider", borderRadius: "8px !important", boxShadow: "none", "&:before": { display: "none" } }} draggable onDragStart={(event) => event.dataTransfer.setData("text/plain", String(index))} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { const from = Number(event.dataTransfer.getData("text/plain")); if (Number.isInteger(from)) onDropAt(from, index); }}>
  <AccordionSummary expandIcon={<ExpandMoreIcon />}><Stack direction={{ xs: "column", md: "row" }} alignItems={{ xs: "stretch", md: "center" }} spacing={1.5} width="100%" pr={1}><DragIndicatorIcon color="disabled" /><Box flex={1}><Stack direction="row" spacing={1} alignItems="center" flexWrap="wrap"><Typography fontWeight={700}>{section.name}</Typography><Chip size="small" variant="outlined" label={section.key} /><Chip size="small" color={section.status === "ACTIVE" ? "success" : "default"} label={section.status === "ACTIVE" ? "Đang bật" : "Đang tắt"} /></Stack><Typography variant="caption" color="text.secondary">Vị trí #{index + 1} · {section.collections.reduce((sum, item) => sum + item.total, 0)} dữ liệu liên kết</Typography></Box><Stack direction="row" alignItems="center" onClick={(event) => event.stopPropagation()}><Tooltip title="Lên"><span><IconButton type="button" size="small" disabled={disabled || index === 0} onClick={() => onMove(index - 1)}><KeyboardArrowUpIcon /></IconButton></span></Tooltip><Tooltip title="Xuống"><span><IconButton type="button" size="small" disabled={disabled || index === total - 1} onClick={() => onMove(index + 1)}><KeyboardArrowDownIcon /></IconButton></span></Tooltip><Switch checked={section.status === "ACTIVE"} disabled={disabled} onChange={onToggle} /><IconButton type="button" size="small" disabled={disabled} onClick={onEdit}><EditOutlinedIcon /></IconButton><IconButton type="button" size="small" color="error" disabled={disabled} onClick={onDelete}><DeleteOutlineIcon /></IconButton></Stack></Stack></AccordionSummary>
  <AccordionDetails sx={{ borderTop: 1, borderColor: "divider" }}><Stack spacing={2.5}><Box><Typography variant="subtitle2">{section.title || "Không có tiêu đề hiển thị"}</Typography>{section.description && <Typography variant="body2" color="text.secondary" mt={0.5}>{section.description}</Typography>}</Box><Stack direction={{ xs: "column", sm: "row" }} spacing={2}>{[["Background", section.backgroundMedia], ["Feature", section.featureMedia]].map(([label, media]) => <Stack key={String(label)} direction="row" spacing={1.5} alignItems="center" flex={1} sx={{ border: 1, borderColor: "divider", borderRadius: 2, p: 1.5 }}><Avatar variant="rounded" src={typeof media === "object" && media ? media.thumbnailUrl ?? media.originalUrl : undefined}><ImageOutlinedIcon /></Avatar><Box><Typography variant="caption" color="text.secondary">{String(label)}</Typography><Typography variant="body2">{typeof media === "object" && media ? media.fileName : "Chưa chọn Media"}</Typography></Box></Stack>)}</Stack><SectionCollections sectionId={section.id} summaries={section.collections} onMutatingChange={onMutatingChange} /></Stack></AccordionDetails>
</Accordion>;
