import React, { useEffect, useState } from "react";
import { Controller, useForm } from "react-hook-form";
import { Alert, Avatar, Box, Button, Dialog, DialogActions, DialogContent, DialogTitle, FormControl, FormControlLabel, FormHelperText, InputLabel, MenuItem, Select, Stack, Step, StepLabel, Stepper, TextField, Typography } from "@mui/material";
import ImageOutlinedIcon from "@mui/icons-material/ImageOutlined";
import LockOutlinedIcon from "@mui/icons-material/LockOutlined";
import { IPageSection, IPageSectionFormValues, pickerOptionToMedia } from "./page-section-types";
import { sectionColorPattern, sectionKeyPattern } from "./page-section-validation";
import { SectionItemPickerDialog } from "./section-item-picker-dialog";

interface Props { open: boolean; section: IPageSection | null; isSaving: boolean; onClose: () => void; onSubmit: (values: IPageSectionFormValues) => Promise<void>; onDirtyChange?: (dirty: boolean) => void; }
const defaults: IPageSectionFormValues = { key: "", name: "", title: "", description: "", backgroundColor: "", backgroundMedia: null, featureMedia: null, status: "ACTIVE" };

export const PageSectionFormDialog: React.FC<Props> = ({ open, section, isSaving, onClose, onSubmit, onDirtyChange }) => {
  const [step, setStep] = useState(0); const [mediaTarget, setMediaTarget] = useState<"backgroundMedia" | "featureMedia" | null>(null); const [keyUnlocked, setKeyUnlocked] = useState(false);
  const form = useForm<IPageSectionFormValues>({ defaultValues: defaults, mode: "onBlur" });
  const { register, control, reset, getValues, setValue, trigger, handleSubmit, formState: { errors, isDirty } } = form;
  useEffect(() => { if (!open) return; reset(section ? { key: section.key, name: section.name, title: section.title ?? "", description: section.description ?? "", backgroundColor: section.backgroundColor ?? "", backgroundMedia: section.backgroundMedia, featureMedia: section.featureMedia, status: section.status } : defaults); setStep(0); setKeyUnlocked(false); }, [open, reset, section]);
  useEffect(() => onDirtyChange?.(open && isDirty), [isDirty, onDirtyChange, open]);
  const next = async () => { const valid = step === 0 ? await trigger(["key", "name"]) : await trigger("backgroundColor"); if (valid) setStep((value) => value + 1); };
  const media = mediaTarget ? getValues(mediaTarget) : null;
  return <><Dialog open={open} onClose={isSaving ? undefined : onClose} fullWidth maxWidth="md"><DialogTitle>{section ? "Chỉnh sửa Section" : "Thêm Section"}</DialogTitle><DialogContent dividers>
    <Stepper activeStep={step} sx={{ mb: 3 }}><Step><StepLabel>Thông tin chung</StepLabel></Step><Step><StepLabel>Giao diện & Media</StepLabel></Step><Step><StepLabel>Xác nhận</StepLabel></Step></Stepper>
    {step === 0 && <Stack spacing={2}><Stack direction={{ xs: "column", sm: "row" }} spacing={2}><TextField fullWidth label="Key" disabled={Boolean(section) && !keyUnlocked} error={Boolean(errors.key)} helperText={errors.key?.message ?? "Ví dụ: hero_banner"} {...register("key", { required: "Key là bắt buộc", pattern: { value: sectionKeyPattern, message: "Chỉ dùng chữ thường, số và dấu gạch dưới" } })} />{section && !keyUnlocked && <Button type="button" startIcon={<LockOutlinedIcon />} onClick={() => setKeyUnlocked(true)}>Mở khóa key</Button>}</Stack><TextField fullWidth label="Tên quản trị" error={Boolean(errors.name)} helperText={errors.name?.message} {...register("name", { required: "Tên Section là bắt buộc", maxLength: { value: 120, message: "Tối đa 120 ký tự" } })} /><TextField fullWidth label="Tiêu đề hiển thị" {...register("title")} /><TextField fullWidth multiline minRows={3} label="Mô tả" {...register("description")} /><Controller name="status" control={control} render={({ field }) => <FormControl fullWidth><InputLabel>Trạng thái</InputLabel><Select {...field} label="Trạng thái"><MenuItem value="ACTIVE">Đang bật</MenuItem><MenuItem value="INACTIVE">Đang tắt</MenuItem></Select></FormControl>} /></Stack>}
    {step === 1 && <Stack spacing={2}><TextField label="Màu nền" placeholder="#FFFFFF" error={Boolean(errors.backgroundColor)} helperText={errors.backgroundColor?.message ?? "Dữ liệu màu của nội dung; có thể để trống."} {...register("backgroundColor", { validate: (value) => !value || sectionColorPattern.test(value) || "Màu phải ở dạng #RRGGBB hoặc #RRGGBBAA" })} /><Stack direction={{ xs: "column", sm: "row" }} spacing={2}>{(["backgroundMedia", "featureMedia"] as const).map((field) => { const value = getValues(field); return <Box key={field} flex={1} sx={{ border: 1, borderColor: "divider", borderRadius: 2, p: 2 }}><Typography fontWeight={700}>{field === "backgroundMedia" ? "Background Media" : "Feature Media"}</Typography><Stack direction="row" spacing={1.5} alignItems="center" mt={1.5}><Avatar src={value?.thumbnailUrl ?? value?.originalUrl} variant="rounded"><ImageOutlinedIcon /></Avatar><Box flex={1}><Typography variant="body2">{value?.fileName ?? "Chưa chọn Media"}</Typography></Box><Button type="button" onClick={() => setMediaTarget(field)}>{value ? "Đổi" : "Chọn"}</Button>{value && <Button type="button" color="error" onClick={() => setValue(field, null, { shouldDirty: true })}>Xóa</Button>}</Stack></Box>; })}</Stack></Stack>}
    {step === 2 && <Stack spacing={2}><Alert severity="info">Kiểm tra thông tin trước khi lưu. Collection sẽ được quản lý sau khi Section được tạo.</Alert><Typography><strong>{getValues("name")}</strong> · {getValues("key")}</Typography><Typography variant="body2" color="text.secondary">{getValues("title") || "Không có tiêu đề hiển thị"}</Typography><Typography variant="body2">Trạng thái: {getValues("status") === "ACTIVE" ? "Đang bật" : "Đang tắt"}</Typography></Stack>}
  </DialogContent><DialogActions><Button type="button" color="secondary" disabled={isSaving} onClick={step === 0 ? onClose : () => setStep((value) => value - 1)}>{step === 0 ? "Hủy" : "Quay lại"}</Button>{step < 2 ? <Button type="button" variant="contained" onClick={() => { void next(); }}>Tiếp tục</Button> : <Button type="button" variant="contained" disabled={isSaving} onClick={() => { void handleSubmit(onSubmit)(); }}>{isSaving ? "Đang lưu..." : "Lưu Section"}</Button>}</DialogActions></Dialog>
  <SectionItemPickerDialog open={Boolean(mediaTarget)} title={mediaTarget === "backgroundMedia" ? "Chọn Background Media" : "Chọn Feature Media"} itemType="MEDIA" multiple={false} selected={media ? [{ id: media.id, itemType: "MEDIA", label: media.fileName, secondary: media.mimeType, imageUrl: media.thumbnailUrl ?? media.originalUrl, originalUrl: media.originalUrl, thumbnailUrl: media.thumbnailUrl, mediumUrl: media.mediumUrl, mimeType: media.mimeType }] : []} onClose={() => setMediaTarget(null)} onConfirm={(items) => { if (mediaTarget && items[0]) setValue(mediaTarget, pickerOptionToMedia(items[0]), { shouldDirty: true }); }} /></>;
};
