import React, { useCallback, useEffect, useState } from "react";
import { Alert, Box, Button, Card, CardContent, Dialog, DialogActions, DialogContent, DialogContentText, DialogTitle, Skeleton, Stack, Typography } from "@mui/material";
import AddOutlinedIcon from "@mui/icons-material/AddOutlined";
import ViewAgendaOutlinedIcon from "@mui/icons-material/ViewAgendaOutlined";
import { IPageSection, IPageSectionFormValues } from "./page-section-types";
import { toSectionPayload } from "./page-section-validation";
import { usePageSections } from "./use-page-sections";
import { PageSectionCard } from "./page-section-card";
import { PageSectionFormDialog } from "./page-section-form-dialog";

export interface PageSectionsManagerState { hasDraftChanges: boolean; isMutating: boolean; }
interface Props { pageId: number; onStateChange?: (state: PageSectionsManagerState) => void; }
const errorMessage = (error: unknown): string => error instanceof Error ? error.message : "Không thể tải danh sách Section.";

export const PageSectionsManager: React.FC<Props> = ({ pageId, onStateChange }) => {
  const sections = usePageSections(pageId); const [editing, setEditing] = useState<IPageSection | null>(null); const [formOpen, setFormOpen] = useState(false); const [formDirty, setFormDirty] = useState(false); const [deleting, setDeleting] = useState<IPageSection | null>(null); const [collectionsMutating, setCollectionsMutating] = useState(false);
  const isMutating = sections.isMutating || collectionsMutating;
  useEffect(() => onStateChange?.({ hasDraftChanges: sections.isOrderDirty || formDirty, isMutating }), [formDirty, isMutating, onStateChange, sections.isOrderDirty]);
  const openCreate = () => { setEditing(null); setFormOpen(true); };
  const submit = async (values: IPageSectionFormValues) => { const payload = toSectionPayload(pageId, editing?.sortOrder ?? sections.sections.length, values); if (editing) await sections.updateSection(editing.id, payload); else await sections.createSection(payload); setFormOpen(false); setFormDirty(false); };
  const handleDrop = (from: number, to: number) => sections.move(from, to);
  const setCollectionMutating = useCallback((active: boolean) => setCollectionsMutating(active), []);
  return <Card sx={{ mt: 3, border: 1, borderColor: "divider", borderRadius: 2, boxShadow: "none" }}><CardContent sx={{ p: { xs: 2, md: 3 } }}><Stack direction={{ xs: "column", sm: "row" }} justifyContent="space-between" alignItems={{ xs: "stretch", sm: "center" }} spacing={2} mb={2.5}><Box><Stack direction="row" spacing={1} alignItems="center"><ViewAgendaOutlinedIcon color="primary" /><Typography variant="h6" fontWeight={700}>Quản lý Section</Typography></Stack><Typography variant="body2" color="text.secondary" mt={0.5}>Cấu hình nội dung, Media, collection và thứ tự hiển thị của từng khu vực.</Typography></Box><Button type="button" variant="contained" startIcon={<AddOutlinedIcon />} disabled={isMutating} onClick={openCreate}>Thêm Section</Button></Stack>
    {sections.query.isLoading ? <Stack spacing={1.5}>{[1, 2, 3].map((item) => <Skeleton key={item} variant="rounded" height={86} />)}</Stack> : sections.query.isError ? <Alert severity="error" action={<Button type="button" onClick={() => { void sections.reload(); }}>Thử lại</Button>}>{errorMessage(sections.query.error)}</Alert> : sections.sections.length === 0 ? <Box sx={{ border: 1, borderStyle: "dashed", borderColor: "divider", borderRadius: 2, py: 7, textAlign: "center" }}><Typography fontWeight={700}>Trang chưa có Section</Typography><Typography variant="body2" color="text.secondary" mt={0.5} mb={2}>Tạo Section đầu tiên để tổ chức nội dung của trang.</Typography><Button type="button" variant="outlined" startIcon={<AddOutlinedIcon />} onClick={openCreate}>Tạo Section</Button></Box> : <Stack spacing={1.5}>{sections.sections.map((section, index) => <PageSectionCard key={section.id} section={section} index={index} total={sections.sections.length} disabled={isMutating} onEdit={() => { setEditing(section); setFormOpen(true); }} onDelete={() => setDeleting(section)} onToggle={() => { void sections.toggleSection(section); }} onMove={(to) => sections.move(index, to)} onDropAt={handleDrop} onMutatingChange={setCollectionMutating} />)}</Stack>}
    {sections.isOrderDirty && <Stack direction="row" justifyContent="flex-end" spacing={1.5} mt={2}><Button type="button" color="secondary" disabled={isMutating} onClick={sections.resetOrder}>Hoàn tác thứ tự</Button><Button type="button" variant="contained" disabled={isMutating} onClick={() => { void sections.saveOrder(); }}>Lưu thứ tự</Button></Stack>}
  </CardContent><PageSectionFormDialog open={formOpen} section={editing} isSaving={sections.isMutating} onClose={() => { setFormOpen(false); setFormDirty(false); }} onSubmit={submit} onDirtyChange={setFormDirty} /><Dialog open={Boolean(deleting)} onClose={() => setDeleting(null)}><DialogTitle>Xóa Section?</DialogTitle><DialogContent><DialogContentText>Section “{deleting?.name}” và toàn bộ liên kết collection của nó sẽ bị xóa khỏi trang.</DialogContentText></DialogContent><DialogActions><Button type="button" onClick={() => setDeleting(null)}>Hủy</Button><Button type="button" color="error" variant="contained" disabled={sections.isMutating} onClick={() => { if (!deleting) return; void sections.deleteSection(deleting.id).then(() => setDeleting(null)); }}>Xóa Section</Button></DialogActions></Dialog></Card>;
};
