import React, { useMemo, useState } from "react";
import { Alert, Avatar, Box, Button, Chip, CircularProgress, Collapse, Dialog, DialogActions, DialogContent, DialogTitle, FormControl, IconButton, InputLabel, MenuItem, Select, Stack, TextField, Typography } from "@mui/material";
import AddOutlinedIcon from "@mui/icons-material/AddOutlined";
import DeleteOutlineIcon from "@mui/icons-material/DeleteOutline";
import KeyboardArrowDownIcon from "@mui/icons-material/KeyboardArrowDown";
import KeyboardArrowUpIcon from "@mui/icons-material/KeyboardArrowUp";
import { IPageSectionCollectionSummary, IPageSectionItem, ISectionPickerOption, PageSectionItemType } from "./page-section-types";
import { SectionItemPickerDialog } from "./section-item-picker-dialog";
import { useSectionCollection } from "./use-section-collection";

const itemView = (item: IPageSectionItem): { label: string; secondary: string; image?: string } => {
  if (item.itemType === "CATEGORY") return { label: item.data.name, secondary: item.data.slug, image: item.data.imageUrl };
  if (item.itemType === "POST") return { label: item.data.title, secondary: `${item.data.typeCode} · ${item.data.slug}`, image: item.data.thumbnailUrl };
  return { label: item.data.fileName, secondary: item.data.mimeType, image: item.data.thumbnailUrl ?? item.data.originalUrl };
};
const toOption = (item: IPageSectionItem): ISectionPickerOption => {
  const view = itemView(item);
  if (item.itemType === "CATEGORY") return { id: item.itemId, itemType: "CATEGORY", label: view.label, secondary: view.secondary, imageUrl: view.image, slug: item.data.slug, status: item.data.status };
  if (item.itemType === "POST") return { id: item.itemId, itemType: "POST", label: view.label, secondary: view.secondary, imageUrl: view.image, slug: item.data.slug, typeCode: item.data.typeCode };
  return { id: item.itemId, itemType: "MEDIA", label: view.label, secondary: view.secondary, imageUrl: view.image, originalUrl: item.data.originalUrl, thumbnailUrl: item.data.thumbnailUrl, mediumUrl: item.data.mediumUrl, mimeType: item.data.mimeType, mediaStatus: item.data.status };
};

const CollectionPanel: React.FC<{ sectionId: number; summary: IPageSectionCollectionSummary; onMutatingChange: (key: string, active: boolean) => void }> = ({ sectionId, summary, onMutatingChange }) => {
  const state = useSectionCollection(sectionId, summary.collection, summary.itemType); const [open, setOpen] = useState(false); const [expanded, setExpanded] = useState(false);
  React.useEffect(() => onMutatingChange(summary.collection, state.isSaving), [onMutatingChange, state.isSaving, summary.collection]);
  const selected = useMemo(() => state.items.map(toOption), [state.items]);
  return <Box sx={{ border: 1, borderColor: "divider", borderRadius: 2, overflow: "hidden" }}><Stack direction={{ xs: "column", sm: "row" }} spacing={1} alignItems={{ xs: "stretch", sm: "center" }} sx={{ px: 2, py: 1.5, bgcolor: "action.hover" }}><Button type="button" color="inherit" onClick={() => setExpanded((value) => !value)} sx={{ justifyContent: "flex-start", flex: 1, textTransform: "none" }}>{expanded ? <KeyboardArrowUpIcon sx={{ mr: 1 }} /> : <KeyboardArrowDownIcon sx={{ mr: 1 }} />}<strong>{summary.collection}</strong></Button><Chip size="small" label={summary.itemType} /><Chip size="small" variant="outlined" label={`${state.items.length} item`} /><Button type="button" size="small" startIcon={<AddOutlinedIcon />} onClick={() => setOpen(true)}>Chọn dữ liệu</Button></Stack><Collapse in={expanded}><Stack spacing={1} p={2}>{state.query.isLoading ? <Box textAlign="center"><CircularProgress size={24} /></Box> : state.query.isError ? <Alert severity="error">Không thể tải collection.</Alert> : state.items.length === 0 ? <Typography color="text.secondary">Collection chưa có dữ liệu.</Typography> : state.items.map((item, index) => { const view = itemView(item); return <Stack key={`${item.itemType}-${item.itemId}`} direction="row" alignItems="center" spacing={1.5} sx={{ border: 1, borderColor: "divider", borderRadius: 1.5, p: 1 }}><Avatar variant="rounded" src={view.image}>{view.label.slice(0, 1)}</Avatar><Box flex={1} minWidth={0}><Typography variant="body2" fontWeight={600} noWrap>{view.label}</Typography><Typography variant="caption" color="text.secondary" noWrap>{view.secondary}</Typography></Box><IconButton size="small" disabled={index === 0} onClick={() => state.move(index, index - 1)}><KeyboardArrowUpIcon /></IconButton><IconButton size="small" disabled={index === state.items.length - 1} onClick={() => state.move(index, index + 1)}><KeyboardArrowDownIcon /></IconButton><IconButton size="small" color="error" onClick={() => state.remove(item.itemId)}><DeleteOutlineIcon /></IconButton></Stack>; })}<Stack direction="row" justifyContent="flex-end" spacing={1}><Button type="button" color="secondary" disabled={!state.isDirty || state.isSaving} onClick={state.reset}>Hoàn tác</Button><Button type="button" variant="contained" disabled={!state.isDirty || state.isSaving} onClick={() => { void state.save(); }}>Lưu collection</Button></Stack></Stack></Collapse><SectionItemPickerDialog open={open} title={`Chọn dữ liệu cho ${summary.collection}`} itemType={summary.itemType} selected={selected} onClose={() => setOpen(false)} onConfirm={state.select} /></Box>;
};

export const SectionCollections: React.FC<{ sectionId: number; summaries: IPageSectionCollectionSummary[]; onMutatingChange: (active: boolean) => void }> = ({ sectionId, summaries, onMutatingChange }) => {
  const [added, setAdded] = useState<IPageSectionCollectionSummary[]>([]); const [dialogOpen, setDialogOpen] = useState(false); const [collection, setCollection] = useState(""); const [itemType, setItemType] = useState<PageSectionItemType>("POST"); const [mutating, setMutating] = useState<Record<string, boolean>>({});
  const all = useMemo(() => [...summaries, ...added.filter((candidate) => !summaries.some((summary) => summary.collection === candidate.collection))], [added, summaries]);
  const setPanelMutating = React.useCallback((key: string, active: boolean) => setMutating((current) => ({ ...current, [key]: active })), []);
  React.useEffect(() => onMutatingChange(Object.values(mutating).some(Boolean)), [mutating, onMutatingChange]);
  const add = () => { const normalized = collection.trim().toLowerCase().replace(/[^a-z0-9_]+/g, "_"); if (!normalized || all.some((item) => item.collection === normalized)) return; setAdded((current) => [...current, { collection: normalized, itemType, total: 0 }]); setCollection(""); setDialogOpen(false); };
  return <Stack spacing={1.5}><Stack direction="row" justifyContent="space-between" alignItems="center"><Typography variant="subtitle2" fontWeight={700}>Collections</Typography><Button type="button" size="small" startIcon={<AddOutlinedIcon />} onClick={() => setDialogOpen(true)}>Thêm collection</Button></Stack>{all.length === 0 ? <Typography variant="body2" color="text.secondary">Chưa có collection. Thêm danh mục, bài viết hoặc thư viện ảnh cho Section.</Typography> : all.map((summary) => <CollectionPanel key={`${summary.collection}-${summary.itemType}`} sectionId={sectionId} summary={summary} onMutatingChange={setPanelMutating} />)}<Dialog open={dialogOpen} onClose={() => setDialogOpen(false)} fullWidth maxWidth="xs"><DialogTitle>Thêm collection</DialogTitle><DialogContent><Stack spacing={2} pt={1}><TextField label="Collection key" value={collection} onChange={(event) => setCollection(event.target.value)} helperText="Ví dụ: featured_posts, gallery" /><FormControl><InputLabel>Loại dữ liệu</InputLabel><Select value={itemType} label="Loại dữ liệu" onChange={(event) => setItemType(event.target.value as PageSectionItemType)}><MenuItem value="CATEGORY">Category</MenuItem><MenuItem value="POST">Post</MenuItem><MenuItem value="MEDIA">Media</MenuItem></Select></FormControl></Stack></DialogContent><DialogActions><Button type="button" onClick={() => setDialogOpen(false)}>Hủy</Button><Button type="button" variant="contained" disabled={!collection.trim()} onClick={add}>Thêm</Button></DialogActions></Dialog></Stack>;
};
