// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/redis/go-redis/v9"
	"go_refine_dashboard_be/internal/controller"
	"go_refine_dashboard_be/internal/infrastructure/repository"
	service5 "go_refine_dashboard_be/internal/usecases/auth/service"
	service3 "go_refine_dashboard_be/internal/usecases/category/service"
	service2 "go_refine_dashboard_be/internal/usecases/media/service"
	service7 "go_refine_dashboard_be/internal/usecases/postmedia/service"
	service6 "go_refine_dashboard_be/internal/usecases/posttype/service"
	"go_refine_dashboard_be/internal/usecases/product/service"
	service4 "go_refine_dashboard_be/internal/usecases/user/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeProductController(db *gorm.DB) *controller.ProductController {
	productRepository := repository.NewProductRepository(db)
	productService := service.NewProductService(productRepository)
	productController := controller.NewProductController(productService)
	return productController
}

func InitializeMediaController(db *gorm.DB) *controller.MediaController {
	mediaRepository := repository.NewMediaRepository(db)
	mediaService := service2.NewMediaService(mediaRepository)
	mediaController := controller.NewMediaController(mediaService)
	return mediaController
}

func InitializeCategoryController(db *gorm.DB) *controller.CategoryController {
	categoryRepository := repository.NewCategoryRepository(db)
	categoryService := service3.NewCategoryService(categoryRepository)
	categoryController := controller.NewCategoryController(categoryService)
	return categoryController
}

func InitializeUserController(db *gorm.DB) *controller.UserController {
	userRepository := repository.NewUserRepository(db)
	userService := service4.NewUserService(userRepository)
	userController := controller.NewUserController(userService)
	return userController
}

func InitializeAuthController(db *gorm.DB, redisClient *redis.Client) *controller.AuthController {
	userRepository := repository.NewUserRepository(db)
	authService := service5.NewAuthService(userRepository, redisClient)
	authController := controller.NewAuthController(authService)
	return authController
}

func InitializePostTypeController(db *gorm.DB, redisClient *redis.Client) *controller.PostTypeController {
	postTypeRepository := repository.NewPostTypeRepository(db)
	postTypeService := service6.NewPostTypeService(postTypeRepository, redisClient)
	postTypeController := controller.NewPostTypeController(postTypeService)
	return postTypeController
}

func InitializePostMediaController(db *gorm.DB, redisClient *redis.Client) *controller.PostMediaController {
	postMediaRepository := repository.NewPostMediaRepository(db)
	postMediaService := service7.NewPostMediaService(postMediaRepository, redisClient)
	postMediaController := controller.NewPostMediaController(postMediaService)
	return postMediaController
}

// wire.go:

var ProductSet = wire.NewSet(repository.NewProductRepository, service.NewProductService, controller.NewProductController)

var MediaSet = wire.NewSet(repository.NewMediaRepository, service2.NewMediaService, controller.NewMediaController)

var CategorySet = wire.NewSet(repository.NewCategoryRepository, service3.NewCategoryService, controller.NewCategoryController)

var UserSet = wire.NewSet(repository.NewUserRepository, service4.NewUserService, controller.NewUserController)

var AuthSet = wire.NewSet(repository.NewUserRepository, service5.NewAuthService, controller.NewAuthController)

var PostTypeSet = wire.NewSet(repository.NewPostTypeRepository, service6.NewPostTypeService, controller.NewPostTypeController)

var PostMediaSet = wire.NewSet(repository.NewPostMediaRepository, service7.NewPostMediaService, controller.NewPostMediaController)
