// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/redis/go-redis/v9"
	"go_refine_dashboard_be/internal/controller"
	"go_refine_dashboard_be/internal/infrastructure/cache"
	"go_refine_dashboard_be/internal/infrastructure/queryservice"
	"go_refine_dashboard_be/internal/infrastructure/repository"
	service5 "go_refine_dashboard_be/internal/usecases/auth/service"
	service3 "go_refine_dashboard_be/internal/usecases/category/service"
	service15 "go_refine_dashboard_be/internal/usecases/imagecontent/service"
	service2 "go_refine_dashboard_be/internal/usecases/media/service"
	service12 "go_refine_dashboard_be/internal/usecases/page/service"
	service13 "go_refine_dashboard_be/internal/usecases/pagemedia/service"
	service14 "go_refine_dashboard_be/internal/usecases/pagesection/service"
	service9 "go_refine_dashboard_be/internal/usecases/post/service"
	service10 "go_refine_dashboard_be/internal/usecases/postcategory/service"
	service7 "go_refine_dashboard_be/internal/usecases/postmedia/service"
	service8 "go_refine_dashboard_be/internal/usecases/postmeta/service"
	service6 "go_refine_dashboard_be/internal/usecases/posttype/service"
	"go_refine_dashboard_be/internal/usecases/product/service"
	service16 "go_refine_dashboard_be/internal/usecases/publicpage/service"
	service11 "go_refine_dashboard_be/internal/usecases/seometa/service"
	service4 "go_refine_dashboard_be/internal/usecases/user/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeProductController(db *gorm.DB) *controller.ProductController {
	productRepository := repository.NewProductRepository(db)
	productService := service.NewProductService(productRepository)
	productController := controller.NewProductController(productService)
	return productController
}

func InitializeMediaController(db *gorm.DB, redisClient *redis.Client) *controller.MediaController {
	mediaRepository := repository.NewMediaRepository(db)
	publicPageCacheRepository := repository.NewPublicPageCacheRepository(db)
	publicPageCacheInvalidator := cache.NewPublicPageCacheInvalidator(redisClient, publicPageCacheRepository)
	mediaService := service2.NewMediaService(mediaRepository, publicPageCacheInvalidator)
	mediaController := controller.NewMediaController(mediaService)
	return mediaController
}

func InitializeCategoryController(db *gorm.DB, redisClient *redis.Client) *controller.CategoryController {
	categoryRepository := repository.NewCategoryRepository(db)
	publicPageCacheRepository := repository.NewPublicPageCacheRepository(db)
	publicPageCacheInvalidator := cache.NewPublicPageCacheInvalidator(redisClient, publicPageCacheRepository)
	categoryService := service3.NewCategoryService(categoryRepository, publicPageCacheInvalidator)
	categoryController := controller.NewCategoryController(categoryService)
	return categoryController
}

func InitializeUserController(db *gorm.DB) *controller.UserController {
	userRepository := repository.NewUserRepository(db)
	userService := service4.NewUserService(userRepository)
	userController := controller.NewUserController(userService)
	return userController
}

func InitializeAuthController(db *gorm.DB, redisClient *redis.Client) *controller.AuthController {
	userRepository := repository.NewUserRepository(db)
	authService := service5.NewAuthService(userRepository, redisClient)
	authController := controller.NewAuthController(authService)
	return authController
}

func InitializePostTypeController(db *gorm.DB, redisClient *redis.Client) *controller.PostTypeController {
	postTypeRepository := repository.NewPostTypeRepository(db)
	postTypeService := service6.NewPostTypeService(postTypeRepository, redisClient)
	postTypeController := controller.NewPostTypeController(postTypeService)
	return postTypeController
}

func InitializePostMediaController(db *gorm.DB, redisClient *redis.Client) *controller.PostMediaController {
	postMediaRepository := repository.NewPostMediaRepository(db)
	publicPageCacheRepository := repository.NewPublicPageCacheRepository(db)
	publicPageCacheInvalidator := cache.NewPublicPageCacheInvalidator(redisClient, publicPageCacheRepository)
	postMediaService := service7.NewPostMediaService(postMediaRepository, redisClient, publicPageCacheInvalidator)
	postMediaController := controller.NewPostMediaController(postMediaService)
	return postMediaController
}

func InitializePostMetaController(db *gorm.DB, redisClient *redis.Client) *controller.PostMetaController {
	postMetaRepository := repository.NewPostMetaRepository(db)
	postMetaService := service8.NewPostMetaService(postMetaRepository, redisClient)
	postMetaController := controller.NewPostMetaController(postMetaService)
	return postMetaController
}

func InitializePostController(db *gorm.DB, redisClient *redis.Client) *controller.PostController {
	postRepository := repository.NewPostRepository(db)
	postCategoryRepository := repository.NewPostCategoryRepository(db)
	publicPageCacheRepository := repository.NewPublicPageCacheRepository(db)
	publicPageCacheInvalidator := cache.NewPublicPageCacheInvalidator(redisClient, publicPageCacheRepository)
	postService := service9.NewPostService(postRepository, postCategoryRepository, redisClient, publicPageCacheInvalidator)
	postController := controller.NewPostController(postService)
	return postController
}

func InitializePostCategoryController(db *gorm.DB, redisClient *redis.Client) *controller.PostCategoryController {
	postCategoryRepository := repository.NewPostCategoryRepository(db)
	postCategoryService := service10.NewPostCategoryService(postCategoryRepository, redisClient)
	postCategoryController := controller.NewPostCategoryController(postCategoryService)
	return postCategoryController
}

func InitializeSEOMetaController(db *gorm.DB, redisClient *redis.Client) *controller.SEOMetaController {
	seoMetaRepository := repository.NewSEOMetaRepository(db)
	entityRegistry := repository.NewEntityRegistry(db)
	publicPageCacheRepository := repository.NewPublicPageCacheRepository(db)
	publicPageCacheInvalidator := cache.NewPublicPageCacheInvalidator(redisClient, publicPageCacheRepository)
	seoService := service11.NewSEOService(seoMetaRepository, entityRegistry, redisClient, publicPageCacheInvalidator)
	seoMetaController := controller.NewSEOMetaController(seoService)
	return seoMetaController
}

func InitializePageController(db *gorm.DB, redisClient *redis.Client) *controller.PageController {
	pageRepository := repository.NewPageRepository(db)
	publicPageCacheRepository := repository.NewPublicPageCacheRepository(db)
	publicPageCacheInvalidator := cache.NewPublicPageCacheInvalidator(redisClient, publicPageCacheRepository)
	pageService := service12.NewPageService(pageRepository, redisClient, publicPageCacheInvalidator)
	pageController := controller.NewPageController(pageService)
	return pageController
}

func InitializePageMediaController(db *gorm.DB, redisClient *redis.Client) *controller.PageMediaController {
	pageMediaRepository := repository.NewPageMediaRepository(db)
	publicPageCacheRepository := repository.NewPublicPageCacheRepository(db)
	publicPageCacheInvalidator := cache.NewPublicPageCacheInvalidator(redisClient, publicPageCacheRepository)
	pageMediaService := service13.NewPageMediaService(pageMediaRepository, db, redisClient, publicPageCacheInvalidator)
	pageMediaController := controller.NewPageMediaController(pageMediaService)
	return pageMediaController
}

func InitializePageSectionController(db *gorm.DB, redisClient *redis.Client) *controller.PageSectionController {
	pageSectionRepository := repository.NewPageSectionRepository(db)
	publicPageCacheRepository := repository.NewPublicPageCacheRepository(db)
	publicPageCacheInvalidator := cache.NewPublicPageCacheInvalidator(redisClient, publicPageCacheRepository)
	pageSectionService := service14.NewPageSectionService(pageSectionRepository, db, publicPageCacheInvalidator)
	pageSectionController := controller.NewPageSectionController(pageSectionService)
	return pageSectionController
}

func InitializeImageContentController(db *gorm.DB, redisClient *redis.Client) *controller.ImageContentController {
	imageContentRepository := repository.NewImageContentRepository(db)
	imageContentService := service15.NewImageContentService(imageContentRepository, db, redisClient)
	imageContentQueryService := queryservice.NewImageContentQueryService(imageContentRepository, redisClient)
	imageContentController := controller.NewImageContentController(imageContentService, imageContentQueryService)
	return imageContentController
}

func InitializePublicPageController(db *gorm.DB, redisClient *redis.Client, publicSiteURL string) *controller.PublicPageController {
	publicPageRepository := repository.NewPublicPageRepository(db)
	publicPageService := service16.NewPublicPageService(publicPageRepository, redisClient, publicSiteURL)
	publicPageController := controller.NewPublicPageController(publicPageService)
	return publicPageController
}

// wire.go:

var ProductSet = wire.NewSet(repository.NewProductRepository, service.NewProductService, controller.NewProductController)

var PublicPageCacheSet = wire.NewSet(repository.NewPublicPageCacheRepository, cache.NewPublicPageCacheInvalidator)

var MediaSet = wire.NewSet(repository.NewMediaRepository, PublicPageCacheSet, service2.NewMediaService, controller.NewMediaController)

var CategorySet = wire.NewSet(repository.NewCategoryRepository, PublicPageCacheSet, service3.NewCategoryService, controller.NewCategoryController)

var UserSet = wire.NewSet(repository.NewUserRepository, service4.NewUserService, controller.NewUserController)

var AuthSet = wire.NewSet(repository.NewUserRepository, service5.NewAuthService, controller.NewAuthController)

var PostTypeSet = wire.NewSet(repository.NewPostTypeRepository, service6.NewPostTypeService, controller.NewPostTypeController)

var PostMediaSet = wire.NewSet(repository.NewPostMediaRepository, PublicPageCacheSet, service7.NewPostMediaService, controller.NewPostMediaController)

var PostMetaSet = wire.NewSet(repository.NewPostMetaRepository, service8.NewPostMetaService, controller.NewPostMetaController)

var PostSet = wire.NewSet(repository.NewPostRepository, repository.NewPostCategoryRepository, PublicPageCacheSet, service9.NewPostService, controller.NewPostController)

var PostCategorySet = wire.NewSet(repository.NewPostCategoryRepository, service10.NewPostCategoryService, controller.NewPostCategoryController)

var SEOMetaSet = wire.NewSet(repository.NewSEOMetaRepository, repository.NewEntityRegistry, PublicPageCacheSet, service11.NewSEOService, controller.NewSEOMetaController)

var PageSet = wire.NewSet(repository.NewPageRepository, PublicPageCacheSet, service12.NewPageService, controller.NewPageController)

var PageMediaSet = wire.NewSet(repository.NewPageMediaRepository, PublicPageCacheSet, service13.NewPageMediaService, controller.NewPageMediaController)

var PageSectionSet = wire.NewSet(repository.NewPageSectionRepository, PublicPageCacheSet, service14.NewPageSectionService, controller.NewPageSectionController)

var ImageContentSet = wire.NewSet(repository.NewImageContentRepository, queryservice.NewImageContentQueryService, service15.NewImageContentService, controller.NewImageContentController)

var PublicPageSet = wire.NewSet(repository.NewPublicPageRepository, service16.NewPublicPageService, controller.NewPublicPageController)
